version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    labels:
      - "dependencies"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      tracing:
        patterns:
          - "go.opentelemetry.io/*"
      golangx:
        patterns:
          - "golang.org/x/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
