version: "2"
run:
  issues-exit-code: 1
  tests: true

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unconvert
    - unused
    - nlreturn
    - bodyclose
    - gocheckcompilerdirectives
    - errname
    - errchkjson
    - unparam
  settings:
    nlreturn:
      block-size: 3

    staticcheck:
      checks:
        - all
        - -ST1003 # struct field ... should be ... (mostly acronyms such as Http -> HTTP)

formatters:
  enable:
    - gofumpt
