{
 "title": "PostgreSQL Exporter",
 "description": "postgres exporter Dashboard for display important postgreSQL metric",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Database", "query": { "query": "label_values(datname)" } },
   { "name": "Interval", "query": "30sec,1m,10m,30m,1h,6h,12h,1d" },
   {
    "name": "app",
    "query": {
     "query": "label_values(fly_instance_up, app)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(pg_stat_database_blks_hit{app=\"$app\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Global Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "PostgreSQL Version",
   "type": "stat",
   "description": "Source: server_version_num",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg_settings_server_version_num{app=\"$app\"})"
    }
   ]
  },
  {
   "title": "Transaction rate",
   "type": "stat",
   "description": "Transactions committed + roolback per minute\n\nSource: pg_stat_database,xact_commit + xact_rollback",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((rate(pg_stat_database_xact_commit{app=\"$app\"}[$Interval])))+sum((rate(pg_stat_database_xact_rollback{app=\"$app\"}[$Interval])))"
    }
   ]
  },
  {
   "title": "Active clients",
   "type": "stat",
   "description": "Clients executing Statements.\n\nSource: pg_stat_activity",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{state=\"active\",app=\"$app\"})"
    }
   ]
  },
  {
   "title": "Shared Buffer Hits",
   "type": "gauge",
   "description": "Shared buffer hits vs reads from disc",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_blks_hit{app=~\"$app\"})/(sum(pg_stat_database_blks_hit{app=~\"$app\"})+sum(pg_stat_database_blks_read{app=~\"$app\"}))*100"
    }
   ]
  },
  {
   "title": "Connections used",
   "type": "gauge",
   "description": "Percentage of max_connections used",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_numbackends{app=\"$app\"})/max(pg_settings_max_connections{app=\"$app\"})"
    }
   ]
  },
  {
   "title": "Commit Ratio",
   "type": "gauge",
   "description": "Transaction committed vs rollbacked",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_xact_commit{app=\"$app\"})/(sum(pg_stat_database_xact_commit{app=\"$app\"}) + sum(pg_stat_database_xact_rollback{app=\"$app\"}))"
    }
   ]
  },
  {
   "title": "Query rate",
   "type": "stat",
   "description": "Statements executed per Minute.\n\nSource: pg_stat_statements.calls",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((rate(pg_stat_statements_calls{app=\"$app\"}[$Interval])))"
    }
   ]
  },
  {
   "title": "Connections by state (stacked)",
   "type": "graph",
   "description": "View: pg_stat_activity",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (state) (pg_stat_activity_count{app=\"$app\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Shared Buffers",
   "type": "stat",
   "description": "Setting: shared_buffers in PostgreSQL.conf",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_shared_buffers_bytes{app=\"$app\"}"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "stat",
   "description": "Setting: max_connections in postgreSQL.conf",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_connections{app=\"$app\"}"
    }
   ]
  },
  {
   "title": "Connections by database (stacked)",
   "type": "graph",
   "description": "View: pg_stat_activity",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) (pg_stat_activity_count{app=\"$app\"})",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "description": "1 Minute rate of transactions committed or rollback.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum ((rate(pg_stat_database_xact_commit[$Interval])))",
     "legendFormat": "committed"
    },
    {
     "expr": "sum ((rate(pg_stat_database_xact_rollback[$Interval])))",
     "legendFormat": "rollback"
    }
   ]
  },
  {
   "title": "Tuples inserts/updates/deletes",
   "type": "graph",
   "description": "Source: pg_stat_database",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum((rate(pg_stat_database_tup_inserted{app=\"$app\"}[$Interval])))",
     "legendFormat": "Inserts"
    },
    {
     "expr": "sum((rate(pg_stat_database_tup_updated{app=\"$app\"}[$Interval])))",
     "legendFormat": "Updates"
    },
    {
     "expr": "sum((rate(pg_stat_database_tup_deleted{app=\"$app\"}[$Interval])))",
     "legendFormat": "Deletes"
    }
   ]
  },
  {
   "title": "I/O Read/Write time",
   "type": "graph",
   "description": "* blk_read_time: Time spent reading data file blocks by backends in this database, in milliseconds\n* blk_write_time: Time spent writing data file blocks by backends in this database, in milliseconds\n\ntrack_io_timings needs to be activated",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum ((rate(pg_stat_database_blk_read_time{app=\"$app\"}[$Interval])))",
     "legendFormat": "blk_read_time"
    },
    {
     "expr": "sum ((rate(pg_stat_database_blk_write_time{app=\"$app\"}[$Interval])))",
     "legendFormat": "blk_read_time"
    }
   ]
  },
  {
   "title": "Tuples fetched/returned",
   "type": "graph",
   "description": "Source: pg_stat_database\n\n* tup_fetched: rows needed to satisfy queries\n* tup_returned: rows read/scanned",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum((rate(pg_stat_database_tup_fetched{app=\"$app\"}[$Interval])))",
     "legendFormat": "Fetched"
    },
    {
     "expr": "sum((rate(pg_stat_database_tup_returned{app=\"$app\"}[$Interval])))",
     "legendFormat": "Returned"
    }
   ]
  },
  {
   "title": "Locks by state",
   "type": "graph",
   "description": "Source: pg_locks",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (mode) (pg_locks_count{app=\"$app\"})",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Deadlocks by database",
   "type": "graph",
   "description": "Should be 0 \n\nSource: pg_stat_database\n\nWith log_lock_waits turned on, deadlocks will be logged to the PostgreSQL Logfiles.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) ((rate(pg_stat_database_deadlocks{app=\"$app\"}[$Interval])))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Temporary files by database",
   "type": "graph",
   "description": "Should be 0. If temporary files are created, it can indicate insufficient work_mem. With log_temp_files the creation of temporary files are logged to the PostgreSQL Logfiles.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) ((rate(pg_stat_database_temp_files{app=\"$app\"}[$Interval])))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Replication lag ",
   "type": "graph",
   "description": "Lag behind master in seconds.\n\nOnly available on a standby System.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(pg_replication_lag{app=\"$app\"})",
     "legendFormat": "lag "
    }
   ]
  },
  {
   "title": "Database: $Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "repeat": "Database",
   "targets": [
    {}
   ]
  },
  {
   "title": "Active clients",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{state=\"active\",app=\"$app\",datname=~\"$Database\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Transaction rate",
   "type": "stat",
   "description": "Transactions committed + roolback per minute\n\nSource: pg_stat_database,xact_commit + xact_rollback",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((rate(pg_stat_database_xact_commit{app=\"$app\",datname=\"$Database\",instance=\"$instance\"}[$Interval])))+sum((rate(pg_stat_database_xact_rollback{app=\"$app\",datname=\"$Database\",instance=\"$instance\"}[$Interval])))"
    }
   ]
  },
  {
   "title": "Shared Buffer Hits",
   "type": "gauge",
   "description": "Shared buffer hits vs reads from disc",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_database_blks_hit{app=~\"$app\",datname=~\"$Database\",instance=\"$instance\"}/(pg_stat_database_blks_hit{app=~\"$app\",datname=~\"$Database\",instance=\"$instance\"}+pg_stat_database_blks_read{app=~\"$app\",datname=~\"$Database\",instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Commit Ratio",
   "type": "gauge",
   "description": "Transaction committed vs rollbacked",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_database_xact_commit{app=\"$app\",datname=~\"$Database\"}/(pg_stat_database_xact_commit{app=\"$app\",datname=~\"$Database\"} + pg_stat_database_xact_rollback{app=\"$app\",datname=~\"$Database\",instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Connections by state (stacked)",
   "type": "graph",
   "description": "View: pg_stat_activity",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (state) (pg_stat_activity_count{app=\"$app\",datname=\"$Database\",instance=\"$instance\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "description": "1 Minute rate of transactions committed or rollback.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{app=\"$app\",datname=\"$Database\",instance=\"$instance\"}[$Interval])",
     "legendFormat": "committed"
    },
    {
     "expr": "rate(pg_stat_database_xact_rollback{app=\"$app\",datname=\"$Database\",instance=\"$instance\"}[$Interval])",
     "legendFormat": "rollback"
    }
   ]
  },
  {
   "title": "Tuples inserts/updates/deletes",
   "type": "graph",
   "description": "Source: pg_stat_database",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_inserted{app=\"$app\",datname=\"$Database\",instance=\"$instance\"}[$Interval])",
     "legendFormat": "Inserts"
    },
    {
     "expr": "rate(pg_stat_database_tup_updated{app=\"$app\",datname=\"$Database\",instance=\"$instance\"}[$Interval])",
     "legendFormat": "Updates"
    },
    {
     "expr": "rate(pg_stat_database_tup_deleted{instance=\"$Instance\",datname=\"$Database\"}[$Interval])",
     "legendFormat": "Deletes"
    }
   ]
  },
  {
   "title": "Tuples fetched/returned",
   "type": "graph",
   "description": "Source: pg_stat_database\n\n* tup_fetched: rows needed to satisfy queries\n* tup_returned: rows read/scanned",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_fetched{app=\"$app\",datname=\"$Database\",instance=\"$instance\"}[$Interval])",
     "legendFormat": "Fetched"
    },
    {
     "expr": "rate(pg_stat_database_tup_returned{app=\"$app\",datname=\"$Database\",instance=\"$instance\"}[$Interval])",
     "legendFormat": "Returned"
    }
   ]
  },
  {
   "title": "Locks by state",
   "type": "graph",
   "description": "Source: pg_locks",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (mode) (pg_locks_count{app=\"$app\",datname=\"$Database\",instance=\"$instance\"})",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Deadlocks by database",
   "type": "graph",
   "description": "Should be 0 \n\nSource: pg_stat_database\n\nWith log_lock_waits turned on, deadlocks will be logged to the PostgreSQL Logfiles.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_deadlocks{app=\"$app\",datname=\"$Database\",instance=\"$instance\"}[$Interval])",
     "legendFormat": "deadlocks"
    }
   ]
  },
  {
   "title": "Temporary files by database",
   "type": "graph",
   "description": "Should be 0. If temporary files are created, it can indicate insufficient work_mem. With log_temp_files the creation of temporary files are logged to the PostgreSQL Logfiles.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_temp_files{app=\"$app\",datname=\"$Database\",instance=\"$instance\"}[$Interval])",
     "legendFormat": "temp_files"
    }
   ]
  }
 ]
}